plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.maven.publish)
}

def publicationGroup = providers.gradleProperty("GROUP").get()
def publicationArtifactId = providers.gradleProperty("POM_ARTIFACT_ID").orElse(project.name).get()
def publicationVersion = providers.gradleProperty("VERSION_NAME").get()

group = publicationGroup
version = publicationVersion

android {
    namespace 'io.groovin.permx'
    compileSdk = libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    kotlin {
        jvmToolchain(21)
    }

    buildFeatures {
        compose = true
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    lint {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }

    testOptions {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx

    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.runtime

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso.core
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(publicationGroup, publicationArtifactId, publicationVersion)

    pom {
        name = 'GroovinPermX'
        description = 'GroovinPermX is a simple and easy permission request helper for Android'
        url = 'https://github.com/gaiuszzang/GroovinPermX'
        licenses {
            license {
                name = 'Apache License 2.0'
                url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
            }
        }
        developers {
            developer {
                id = 'gaiuszzang'
                name = 'gaiuszzang'
                url = 'https://github.com/gaiuszzang'
            }
        }
        scm {
            url = 'https://github.com/gaiuszzang/GroovinPermX'
            connection = 'scm:git:git://github.com/gaiuszzang/GroovinPermX.git'
            developerConnection = 'scm:git:ssh://git@github.com/gaiuszzang/GroovinPermX.git'
        }
    }
}
